# Generated by Django 3.0.2 on 2020-01-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapi', '0002_auto_20200109_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='Products',
        ),
        migrations.AlterModelTable(
            name='products',
            table='items',
        ),
    ]
