# Generated by Django 3.0.2 on 2020-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapi', '0003_auto_20200109_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='item_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='item_image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='months',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='origin',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='item_title',
            field=models.TextField(null=True),
        ),
    ]
